services:
  app:
    build: .
    environment:
      - SPRING_DATASOURSE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURSE_USERNAME=postgres
      - SPRING_DATASOURSE_PASSWORD=saturday1Spring
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: app_test
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: saturday1Spring
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped